version: "3"

services:
  db:
    image: postgres:14.7
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data

  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./static_volume:/app/static
      - ./media_volume:/app/media
    ports:
      - "${API_PORT}:8000"
    env_file:
      - .env
    command: gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 core.wsgi:application

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file:
      - .env
    restart: always
    command: python3 bot.py
  
  
volumes:
  static_volume:
  media_volume:
  db:
