# Generated by Django 5.1.2 on 2024-10-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_receipt_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
