# Generated by Django 5.1.2 on 2024-10-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='books/content/'),
        ),
    ]
