# Generated by Django 5.1.2 on 2024-11-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_as_bonus', to='books.book')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_books', to='books.book')),
            ],
        ),
    ]
