# Generated by Django 5.1.2 on 2024-12-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_bonusbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lang',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
